FROM openjdk:11
RUN apt-get update
##RUN apt-get install -y openjdk-11-jdk
ARG JAR_FILE=ecommerce-0.0.1-SNAPSHOT.jar
ARG YML_FILE=application.yml
WORKDIR vijay
COPY ${JAR_FILE} ecommerce.jar
COPY ${YML_FILE} app.yml
RUN chmod 777 ecommerce.jar
EXPOSE 1201
ENTRYPOINT ["java", "-Dspring.config.location=app.yml","-jar", "ecommerce.jar"]